### PR TITLE
File/Directory creation

### LINKED ISSUE #4: Show an error for name collision
When creating a folder that already exists, we can display an error message to notify the user why nothing happened.

### LINKED ISSUE #14: "Commands->Edit New" does not work
It does nothing

### PR DESCRIPTION
**Pull request by ocerman**
Implemented function "edit new file" ( FIX #14 )
Added alerts when directory already exists and when directory cannot be created ( FIX #4 )

### CODE REVIEW

File: src/GenesisMakeFileWindow.cpp [hunk 1]
```diff
@@ -137,21 +158,67 @@ void GenesisMakeDirWindow::MessageReceived(BMessage* message)
...
 	BString dir;
 	dir.SetTo(dirpath);
 	dir+="/";
 	dir+=dirname;
 
-	if (create_directory(dir.String(), 0777)==B_OK)		// TODO: jo a 0777?
+	BEntry *entry = new BEntry(dir);
+	if (entry->Exists() && entry->IsDirectory())
+	{
+		BAlert *alert = new BAlert("Cannot create new folder","Folder already exists","OK",NULL,NULL,B_WIDTH_AS_USUAL,B_INFO_ALERT);
```
Comment (humdingerb) [inline src/GenesisMakeFileWindow.cpp]: The first argument to BAlert is currently not exposed in the GUI, but might one day (by some Decorator). I'd go for a short title, like "_Error creating folder_".

The text of the alert itself can be more user-centric, elaborate. Like: "_A folder with that name already exists._"
Maybe even but the folder name into the text: "_The folder 'name-of-folder' already exists._"

File: src/GenesisMakeFileWindow.cpp [hunk 2]
```diff
@@ -137,21 +158,67 @@ void GenesisMakeDirWindow::MessageReceived(BMessage* message)
...
+	}
+	
+	status_t status = create_directory(dir.String(), 0777);
+	if (status == B_OK)
+		return 1;
+		
+	BString errormsg;
+	switch (status){
+		case B_NOT_A_DIRECTORY:
+			errormsg.SetToFormat("Entry '%s' already exists", dirname);
```
Comment (humdingerb) [inline src/GenesisMakeFileWindow.cpp]: Maybe a bit too technical. As this alert only appears when it's not a folder, we may be more specific, like: _"A file '%s' already exists."_

File: src/GenesisMakeFileWindow.cpp [hunk 3]
```diff
@@ -137,21 +158,67 @@ void GenesisMakeDirWindow::MessageReceived(BMessage* message)
...
 ////////////////////////////////////////////////////////////////////////
 {
 	BString dir;
 	dir.SetTo(dirpath);
 	dir+="/";
 	dir+=dirname;
 
-	if (create_directory(dir.String(), 0777)==B_OK)		// TODO: jo a 0777?
+	BEntry *entry = new BEntry(dir);
+	if (entry->Exists() && entry->IsDirectory())
```
Comment (humdingerb) [inline src/GenesisMakeFileWindow.cpp:171]: You may want to test, if the existing entry is a symlink to a folder. When the symlink is a file, it works: the Entry-already-exists-Alert pops up. In case of symlinked folder, nothing is shown.

File: src/GenesisMakeFileWindow.cpp [hunk 4]
```diff
@@ -137,21 +158,67 @@ void GenesisMakeDirWindow::MessageReceived(BMessage* message)
...
+	switch (status){
+		case B_NOT_A_DIRECTORY:
+			errormsg.SetToFormat("Entry '%s' already exists", dirname);
+			break;
+		default:
+			errormsg.SetTo("Unknown error");
+			break;
+	}
+
+	BAlert *alert = new BAlert("Cannot create new folder",errormsg.String(),"OK",NULL,NULL,B_WIDTH_AS_USUAL,B_WARNING_ALERT);
```
Comment (humdingerb) [inline src/GenesisMakeFileWindow.cpp]: As above, the tile may be nicer as "_Error creating folder_".

File: src/GenesisMakeFileWindow.cpp [hunk 5]
```diff
@@ -137,21 +158,67 @@ void GenesisMakeDirWindow::MessageReceived(BMessage* message)
...
+	BDirectory *dir = new BDirectory(path);
 
+	status_t status = dir->CreateFile(filename, NULL, true);
+	if (status == B_OK)
+		return 1;
+	
+	BString errormsg;
+	switch (status){
+		case B_FILE_EXISTS:
+			errormsg.SetToFormat("File '%s' already exists", filename);
```
Comment (humdingerb) [inline src/GenesisMakeFileWindow.cpp]: You may want to check if it's a folder here as well, and show a different message if it is.

File: src/GenesisMakeFileWindow.cpp [hunk 6]
```diff
@@ -137,21 +158,67 @@ void GenesisMakeDirWindow::MessageReceived(BMessage* message)
...
+			break;
+		default:
+			errormsg.SetTo("Unknown error");
+			break;
+	}
+	
+	BAlert *alert = new BAlert("Cannot create new file",errormsg.String(),"OK",NULL,NULL,B_WIDTH_AS_USUAL,B_WARNING_ALERT);
```
Comment (humdingerb) [inline src/GenesisMakeFileWindow.cpp]: Again, shorter title, like: _"Error creating file"_

**Comment by ocerman** [comment]
@humdingerb I have pushed another commit with updated alerts

**Comment by humdingerb** [comment]
Thanks!
